### ISSUE TITLE
 Velvetdb backend not registered: xodus

### ISSUE THREAD

**Issue by ghost** [zakgof/velvetdb#5]
**Velvetdb backend not registered: xodus  is the error** 

private static IVelvetEnvironment createEnv() {
		try {
			PATH = Files.createTempDirectory("velvet").toString();
			new File(PATH).mkdirs();
			IVelvetEnvironment env = VelvetFactory
					.openCaching("velvetdb://xodus/" + PATH.replace(File.separatorChar, '/'));
			return env;
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(-1);
			return null;
		}

}
IVelvetEnvironment env = createEnv();

trigger 
com.zakgof.db.velvet.VelvetException: Velvetdb backend not registered: xodus
	at com.zakgof.db.velvet.VelvetFactory.lambda$open$1(VelvetFactory.java:42)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.zakgof.db.velvet.VelvetFactory.open(VelvetFactory.java:42)

i tested xodus as well with all the correct dependencies and it work .
try (Environment env = Environments.newInstance("/./me/.myAppData")) {
		    env.executeInTransaction(txn -> {
		        final Store store = env.openStore("Messages", StoreConfig.WITHOUT_DUPLICATES, txn);
		        store.put(txn, StringBinding.stringToEntry("Hello"), StringBinding.stringToEntry("World!"));
		    });
		}
May you help?

regards
david

**Comment by zakgof** [comment]
The error indicates that **velvetdb-xodus** is not on classpath. Both **velvetdb** and **velvetdb-xodus** should be present.
Can you share your setup (maven/gradle/etc ?)

**Comment by dguimard** [comment]
You are right , i thought the core was grabing all dependency, i really like your vision , you statement is very right ! i am doing a tools that generate relationship from uml2.

**Comment by dguimard** [comment]
solved 
<dependency>
			<groupId>com.github.zakgof</groupId>
			<artifactId>velvetdb-core</artifactId>
			<version>0.9.0</version>
		</dependency>
		
			<dependency>
			<groupId>com.github.zakgof</groupId>
			<artifactId>velvetdb-xodus</artifactId>
			<version>0.9.0</version>
		</dependency>
